name: GitHub-Profile-3D-Contrib
on:
  schedule:
     - cron: "0 18 * * 0"  # 매주 일요일 UTC 18:00 (한국 월요일 03:00)
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_TOKEN }}  # 여기 추가!
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}  # 여기 변경!
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name moonjun1
          git config user.email puls55555@naver.com
          git add -A .
          git commit -m "generated"
          git push
